# Use root/example as user/password credentials
version: '3.8'

services:

  mysql:
    image: mysql:8.0.28
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: pet_user
      MYSQL_PASSWORD: db_password123
      MYSQL_DATABASE: petshop_db
      MYSQL_ROOT_PASSWORD: root_ps